AWSTemplateFormatVersion: 2010-09-09
Description: My PHP Application
Transform: AWS::Serverless-2016-10-31
Resources:
  phpserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-phpserver
      Description: PHP Webserver
      CodeUri: src/php/lumen/public
      Runtime: provided
      Handler: index.php
      MemorySize: 1024
      Timeout: 30
      Tracing: Active
      Layers:
        - arn:aws:lambda:eu-west-1:645489824668:layer:PHP72-Layer:1
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY